version: "3.8"
services:
  server:
    build: './server'
    container_name: server
    environment:
      NODE_ENV: development
    ports:
      - 5000:5000

    env_file:
      - ./server/.env

    volumes:
      - './server/:/app/server'

  client:
    build: './client'
    container_name: client
    ports:
      - 3000:3000

    env_file:
      - ./client/.env

    volumes:
      - './client/:/app/client'
    stdin_open: true
    tty: true
    depends_on:
      - server
    
