version: "3.8"
services:
# MongoDB service
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "mongodb_db:/data/db"


  # MongoDB dashboard service
  mongo-express:
    restart: always
    image: mongo-express
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    ports:
      - "8081:8081"
    volumes:
      - "mongodb_db:/data/db"
    depends_on:
      - mongo
  

 # Node.js&Express server service
  server:
    build: './server'
    container_name: server
    environment:
      NODE_ENV: development
    ports:
      - 5000:5000

    env_file:
      - ./server/.env
    volumes:
      - './server/:/app/server'
    depends_on:
      - mongo
      - mongo-express

 # React client service
  client:
    build: './client'
    container_name: client
    ports:
      - 3000:3000

    env_file:
      - ./client/.env

    volumes:
      - './client/:/app/client'
    stdin_open: true
    tty: true
    depends_on:
      - server

volumes:
  mongodb_db:
       driver: local
    
